
SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

CREATE EXTENSION IF NOT EXISTS "pgsodium" WITH SCHEMA "pgsodium";

COMMENT ON SCHEMA "public" IS 'standard public schema';

CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";

CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";

CREATE OR REPLACE FUNCTION "public"."incrementchapterindex"("minrank" integer, "project_id" "uuid") RETURNS "void"
    LANGUAGE "sql"
    AS $$
  update chapters
  set index = index + 1
  where index >= minrank AND project = project_id;
$$;

ALTER FUNCTION "public"."incrementchapterindex"("minrank" integer, "project_id" "uuid") OWNER TO "postgres";

CREATE OR REPLACE FUNCTION "public"."incrementitemindex"("minrank" integer, "chapter_id" "uuid") RETURNS "void"
    LANGUAGE "sql"
    AS $$
  update items
  set rank_in_chapter = rank_in_chapter + 1
  where rank_in_chapter >= minrank AND chapter = chapter_id;
$$;

ALTER FUNCTION "public"."incrementitemindex"("minrank" integer, "chapter_id" "uuid") OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";

CREATE TABLE IF NOT EXISTS "public"."chapters" (
    "chapter_id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "title" "text",
    "descriptions" "text",
    "project" "uuid",
    "index" integer
);

ALTER TABLE "public"."chapters" OWNER TO "postgres";

COMMENT ON TABLE "public"."chapters" IS 'The chapters of a project';

COMMENT ON COLUMN "public"."chapters"."index" IS 'The index of the chapter';

CREATE TABLE IF NOT EXISTS "public"."item-types-enum" (
    "id" bigint NOT NULL,
    "type" "text"
);

ALTER TABLE "public"."item-types-enum" OWNER TO "postgres";

COMMENT ON TABLE "public"."item-types-enum" IS 'Enum of the different types of items';

ALTER TABLE "public"."item-types-enum" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."item-types_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."items" (
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "type" bigint,
    "chapter" "uuid" NOT NULL,
    "rank_in_chapter" integer NOT NULL,
    "outline" "text",
    "final" "text",
    "item_id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL
);

ALTER TABLE "public"."items" OWNER TO "postgres";

COMMENT ON TABLE "public"."items" IS 'all the text items';

COMMENT ON COLUMN "public"."items"."rank_in_chapter" IS 'The rank within a chapter';

ALTER TABLE "public"."items" ALTER COLUMN "rank_in_chapter" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."items_rank_in_chapter_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."projects" (
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text" NOT NULL,
    "project_id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL
);

ALTER TABLE "public"."projects" OWNER TO "postgres";

COMMENT ON TABLE "public"."projects" IS 'The list of projects of a user';

COMMENT ON COLUMN "public"."projects"."name" IS 'The name of the project';

ALTER TABLE ONLY "public"."chapters"
    ADD CONSTRAINT "chapters_pkey" PRIMARY KEY ("chapter_id");

ALTER TABLE ONLY "public"."item-types-enum"
    ADD CONSTRAINT "item-types_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."items"
    ADD CONSTRAINT "items_pkey" PRIMARY KEY ("item_id");

ALTER TABLE ONLY "public"."projects"
    ADD CONSTRAINT "projects_pkey" PRIMARY KEY ("project_id");

ALTER TABLE ONLY "public"."chapters"
    ADD CONSTRAINT "public_chapters_project_fkey" FOREIGN KEY ("project") REFERENCES "public"."projects"("project_id");

ALTER TABLE ONLY "public"."items"
    ADD CONSTRAINT "public_items_chapter_fkey" FOREIGN KEY ("chapter") REFERENCES "public"."chapters"("chapter_id");

ALTER TABLE ONLY "public"."items"
    ADD CONSTRAINT "public_items_type_fkey" FOREIGN KEY ("type") REFERENCES "public"."item-types-enum"("id");

CREATE POLICY "Enable all for authenticated users only" ON "public"."chapters" TO "authenticated" USING (true);

CREATE POLICY "Enable insert for authenticated users only" ON "public"."chapters" FOR INSERT TO "authenticated" WITH CHECK (true);

CREATE POLICY "Enable insert for authenticated users only" ON "public"."items" TO "authenticated" USING (true);

CREATE POLICY "Enable read access for all users" ON "public"."items" FOR SELECT TO "authenticated" USING (true);

CREATE POLICY "Enable select for authenticated users only" ON "public"."chapters" FOR SELECT TO "authenticated" USING (true);

ALTER TABLE "public"."chapters" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."item-types-enum" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."items" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."projects" ENABLE ROW LEVEL SECURITY;

ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";

GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";

GRANT ALL ON FUNCTION "public"."incrementchapterindex"("minrank" integer, "project_id" "uuid") TO "anon";
GRANT ALL ON FUNCTION "public"."incrementchapterindex"("minrank" integer, "project_id" "uuid") TO "authenticated";
GRANT ALL ON FUNCTION "public"."incrementchapterindex"("minrank" integer, "project_id" "uuid") TO "service_role";

GRANT ALL ON FUNCTION "public"."incrementitemindex"("minrank" integer, "chapter_id" "uuid") TO "anon";
GRANT ALL ON FUNCTION "public"."incrementitemindex"("minrank" integer, "chapter_id" "uuid") TO "authenticated";
GRANT ALL ON FUNCTION "public"."incrementitemindex"("minrank" integer, "chapter_id" "uuid") TO "service_role";

GRANT ALL ON TABLE "public"."chapters" TO "anon";
GRANT ALL ON TABLE "public"."chapters" TO "authenticated";
GRANT ALL ON TABLE "public"."chapters" TO "service_role";

GRANT ALL ON TABLE "public"."item-types-enum" TO "anon";
GRANT ALL ON TABLE "public"."item-types-enum" TO "authenticated";
GRANT ALL ON TABLE "public"."item-types-enum" TO "service_role";

GRANT ALL ON SEQUENCE "public"."item-types_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."item-types_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."item-types_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."items" TO "anon";
GRANT ALL ON TABLE "public"."items" TO "authenticated";
GRANT ALL ON TABLE "public"."items" TO "service_role";

GRANT ALL ON SEQUENCE "public"."items_rank_in_chapter_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."items_rank_in_chapter_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."items_rank_in_chapter_seq" TO "service_role";

GRANT ALL ON TABLE "public"."projects" TO "anon";
GRANT ALL ON TABLE "public"."projects" TO "authenticated";
GRANT ALL ON TABLE "public"."projects" TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";

RESET ALL;
